### ISSUE TITLE
500 error when adding account to learn from

### ISSUE THREAD

**Issue by jshholland** [Lynnesbian/FediBooks#17]
**What happened?**
Having created a new bot, if I try to add an account for it to learn from, I get a 500 Internal Server Error.

**How did it happen?**
1. Create a bot.
2. Click on 'Accounts learned from' icon, then 'Add account'.
3. Enter my account name (which is on a Pleroma instance).

**Where did it happen?**
https://fedibooks.com/bot/accounts/add

**Expected behavior**
The bot starts learning from @josh@squ.alid.pw.

**Error message**
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by Lynnesbian** [comment]
Should be fixed now, can you check?

**Comment by ibrokemypie** [comment]
I had the same issue and it seems to be fixed now for me

**Comment by jshholland** [comment]
Yep, looks fixed for me too now.
